version: '3.8'

services:
  flask-receiver:
    build: .
    container_name: flask-receiver
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "${PORT:-5001}:${PORT:-5000}"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./certs:/app/certs
    networks:
      - flask-network
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:${PORT:-5000}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  flask-network:
    driver: bridge

volumes:
  logs:
  data:
  certs:

